import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Main } from 'src/components/Main'

const inter = Inter({ subsets: ['latin'] })

export default function Home( props ) {
  const { count, isShow, handleClick, handleDisplay,text, array, handleChange , handleAdd } = props;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isShow ? <h1>{count}</h1> : null}
      <button
        onClick={handleClick}>
        ボタン
      </button>
      <button
        onClick={handleDisplay}
      >
        {isShow ? "非表示" : "表示"}
      </button>
      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>
      <Main page="index" />
    </>
  )
}
